blank_issues_enabled: true
contact_links:
  - name: "â“ Q&A - GitHub Discussions"
    url: https://github.com/track-asia/trackasia-react-native/discussions/categories/q-a
    about: If you have a question about using TrackAsia React Native
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join `#trackasia-react-native` on the Open Street Map Slack"